name: Publish to GitHub Packages (Java 8)

on:
  push:
    branches: [ master ]      # every commit to master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
          server-id: GitHubPackages
          server-username: ${{ secrets.GPR_USER }}
          server-password: ${{ secrets.GPR_KEY }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ secrets.GPR_USER }}
          TOKEN:    ${{ secrets.GPR_KEY }}
        run: ./gradlew clean publish --no-daemon
