name: Publish to GitHub Packages

on:
  push:
    branches:
      - master          # run on every commit to master
  workflow_dispatch:     # allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install Temurin JDK 11
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          server-id: GitHubPackages                  # ties into Gradle publishing creds
          server-username: ${{ secrets.GPR_USER }}  # not strictly required but harmless
          server-password: ${{ secrets.GPR_KEY }}

      # 3) Cache Gradle wrapper and dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # 4) Build and publish
      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ secrets.GPR_USER }}  # picked up by build.gradle credentials block
          TOKEN:    ${{ secrets.GPR_KEY }}
        run: ./gradlew clean publish --no-daemon
